apiVersion: kubeai.my.domain/v1beta1
kind: Kubeops
metadata:
  labels:
    app.kubernetes.io/name: src
    app.kubernetes.io/managed-by: kustomize
  name: kubeops-sample
spec:
  # TODO(user): Add fields here
