# permissions for end users to view kubeops.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: kubeops-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: src
    app.kubernetes.io/part-of: src
    app.kubernetes.io/managed-by: kustomize
  name: kubeops-viewer-role
rules:
- apiGroups:
  - kubeai.my.domain
  resources:
  - kubeops
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubeai.my.domain
  resources:
  - kubeops/status
  verbs:
  - get
