# permissions for end users to view kubeplaceholder11s.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: kubeplaceholder11-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: a1
    app.kubernetes.io/part-of: a1
    app.kubernetes.io/managed-by: kustomize
  name: kubeplaceholder11-viewer-role
rules:
- apiGroups:
  - kubeai.my.domain
  resources:
  - kubeplaceholder11s
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubeai.my.domain
  resources:
  - kubeplaceholder11s/status
  verbs:
  - get
